[toolchain]
anchor_version= "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solnado = "Ag36R1MUAHhyAYB96aR3JAScLqE6YFNau81iCcf2Y6RC"

[programs.devnet]
solnado = "Ag36R1MUAHhyAYB96aR3JAScLqE6YFNau81iCcf2Y6RC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nico/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
